name = "StringTheoryFormalization"
version = "0.1.0"
defaultTargets = ["StringTheoryFormalization"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"

[[lean_lib]]
name = "StringTheoryFormalization"
roots = ["StringTheoryFormalization"]

[[lean_lib]]
name = "StringTheoryFormalizationTests"
roots = ["Tests"]
