/-
Stream 2 · P2.3 — Reflections in `(−2)`-vectors are lattice isometries.

Sources (Tier L), Huybrechts, *Lectures on K3 Surfaces*
(`papers/foundations/huybrechts_K3Global.txt`):
* Ch. 7 §5.4 (lines 6031–6043): `s_δ(v) = v − 2 (v.δ)/(δ)² · δ`, which for `(δ)² = −2` is
  `v + (v.δ) δ` — the form used below — and elements of `O(Λ)` are written as products of
  reflections `s_{δᵢ}` with `(δᵢ)² = −2`;
* Ch. 6 (line 5400): for a degeneration smoothing an `A₁`-singularity "the monodromy T is the
  reflection s_δ with δ the cohomology class corresponding to the exceptional (−2)-curve"
  (Picard–Lefschetz).
That the simple reflections generate the Weyl group of `E8` is standard (Tier L, not
proved here).

Tier A here, any rank `n`, integer lattice with symmetric Gram matrix `L`:
* with `s_v = 1 + v vᵀ L`, the orchestrator verified symbolically (sympy, generic rank 3) that
  `s_vᵀ L s_v − L = (2 + vᵀLv) · L v vᵀ L` and `s_v² − 1 = (2 + vᵀLv) · v vᵀ L`;
  so for `vᵀ L v = −2`, `s_v` is an isometry of `L` and an involution;
* in `E8(−1)` every simple root `eᵢ` has norm `−2`, so each simple reflection is an
  isometry of `E8(−1)` — the Weyl reflections of the `E8(−1)` summand of the K3 lattice.

## Physical background

Reflections in `(−2)`-classes are the algebraic shadow of a specific piece of K3
geometry: smoothing an `A₁`-singularity of a degenerating family of K3 surfaces produces
an exceptional `(−2)`-curve, and the monodromy of that degeneration acts on `H²(X,ℤ)` as
exactly the reflection in the class of that curve — "the monodromy `T` is the reflection
`s_δ` with `δ` the cohomology class corresponding to the exceptional `(−2)`-curve over the
singularity" (Huybrechts, Ch. 6, `papers/foundations/huybrechts_K3Global.txt`, line 5400,
read for this file). More generally, every orientation-preserving isometry of the K3
lattice factors as a product of such reflections (Cartan–Dieudonné, quoted at Ch. 7 §5.4,
lines 6031–6043, also read for this file) — this is the mechanism by which the "modular
group" `O⁺(Γ³'¹⁹)` of `K3T2Signature.lean`'s moduli-space quotient is generated. This file
proves only the elementary two-line linear-algebra fact that makes any single such
reflection well-defined: it is an isometry and an involution exactly when the reflecting
vector has norm `−2`.

## Mathematical content

For any integer Gram matrix `L` of rank `n` and vector `v`, `reflection L v := 1 + v vᵀ L`
is the candidate reflection matrix (`s_v x = x + ⟨x,v⟩_L · v` in coordinates), and
`latticeNorm L v := vᵀLv` is `v`'s self-pairing. `vecMulVec_mul_self` is a pure matrix
identity, true for *any* `L` (symmetric or not): `(v vᵀ) L (v vᵀ) = (vᵀLv) • (v vᵀ)`.
`reflection_isometry` proves that *when* `latticeNorm L v = -2` and `L` is symmetric,
`s_vᵀ L s_v = L`, i.e. `s_v` really is an isometry of the lattice; `reflection_involution`
proves that under the same norm hypothesis (symmetry not even needed here), `s_v² = 1`.
`e8Neg_simpleRoot_norm` computes that each of the 8 standard basis vectors has norm `−2`
in `e8Neg`, and `e8Neg_weyl_isometry` combines this with `reflection_isometry` to conclude
each of the 8 *simple* reflections is an isometry of `E8(−1)`.

**Not proved here** — this is the file's central scope limitation: the general sympy-
verified polynomial identity `s_vᵀ L s_v − L = (2 + vᵀLv) · L v vᵀ L` quoted in the module
docstring above is a **symbolic check** (BOOK_BIBLE §2), not a Lean theorem — it is not
re-derived for general `vᵀLv` inside this file, only used as motivation for *why* the
hypothesis `vᵀLv = −2` is exactly what makes the correction term vanish. What Lean
actually proves is the two consequences *at* that hypothesis (`reflection_isometry`,
`reflection_involution`), not the general identity itself. Also not proved: that the full
Weyl group of `E8` is generated by these reflections (Tier L, stated in the module
docstring, not derived); `e8Neg_weyl_isometry` covers only the 8 *simple* roots
(`Pi.single i 1`), not the 240 roots of `E8`, so it does not by itself establish that the
whole Weyl group preserves the form (that needs the group-generation fact, which is not
proved here); and no claim that `reflection` implements the *monodromy* operator of an
actual degenerating family — only that it is the abstract lattice map Huybrechts's
geometric statement (line 5400) is comparing monodromy to.

## Proof techniques

`vecMulVec_mul_self` is proved by unfolding `latticeNorm` and chaining four Mathlib
matrix-algebra lemmas (`vecMulVec_mul`, `vecMulVec_mul_vecMulVec`, `dotProduct_mulVec`,
`vecMulVec_smul`) — a rewrite, not a case split. `reflection_isometry` and
`reflection_involution` both first isolate the "correction term"
`(v vᵀ L)(v vᵀ L) = (-2) • (v vᵀ L)` as a `have` (using `vecMulVec_mul_self` at the
hypothesis `vᵀLv = -2`), then expand the defining product of `reflection L v` with itself
(or with its transpose) using `noncomm_ring`/`add_mul`/`mul_add`, substitute the
correction term, and close with `abel`. `e8Neg_simpleRoot_norm` and `e8Neg_weyl_isometry`
are direct instantiations at each of the 8 standard basis vectors (`fin_cases i`), not new
arguments.

## Related declarations

`reflection_isometry` shares its key algebraic shape — `Mᵀ L M = L` — with the congruence
condition `DualScaleStream2.TDuality.IsODD` uses to define orthogonal-w.r.t.-`η`
transformations, and correspondingly shares proof lemmas (`Matrix.transpose_mul`,
`Matrix.transpose_one`) with `DFT.genMetric_symm` and `TDuality.isODD_inv_isODD`/
`isODD_mul` (atlas "shared foundations"): both are instances of the same general pattern
"a matrix preserves a bilinear form iff it satisfies this congruence identity", applied to
different forms (`L` here, `η` there). `reflection_involution` is an atlas *unification
candidate* (cosine 0.36, dep-Jaccard 0.003 — similar statement, essentially independent
proof) with `Lean5Corpus.Problems.MukaiMonodromy.buscher_reflection_involution`: an
independent re-proof, in a different library, of an involution property for a
differently-defined reflection-like map (the Buscher T-duality transformation), not the
same theorem.
-/
import DualScaleStream2.Lattice.E8

namespace DualScaleStream2.Lattice

open Matrix

variable {n : ℕ}

/-- Reflection matrix `s_v = 1 + v vᵀ L` (so `s_v x = x + ⟨x, v⟩ v` with `⟨x, v⟩ = vᵀ L x`).
This is the candidate for the reflection `sδ : x ↦ x − 2(x·δ)/(δ)² · δ` of Huybrechts's
Ch. 7 §5.4 formula, specialized to the case `(δ)² = −2` where `−2/(δ)² = 1`: it is *defined*
for every `v`, but only actually behaves like a lattice reflection (isometry, involution)
under that norm hypothesis — see `reflection_isometry`/`reflection_involution`. -/
def reflection (L : Gram n) (v : Fin n → ℤ) : Gram n :=
  1 + vecMulVec v v * L

/-- The self-pairing (norm) `vᵀLv` of `v` under the bilinear form `L`. -/
def latticeNorm (L : Gram n) (v : Fin n → ℤ) : ℤ := v ⬝ᵥ (L *ᵥ v)

/-- **Key identity**: `v vᵀ L v vᵀ = (vᵀLv) • v vᵀ` as matrices, for any Gram matrix `L`
(no symmetry needed — both sides expand to `v i * (vᵀ L v) * v j`). This is the one
computation both `reflection_isometry` and `reflection_involution` reduce to, at their
respective hypothesis `vᵀLv = -2`. -/
theorem vecMulVec_mul_self (L : Gram n) (v : Fin n → ℤ) :
    vecMulVec v v * L * vecMulVec v v = (latticeNorm L v) • vecMulVec v v := by
  unfold latticeNorm
  rw [vecMulVec_mul, vecMulVec_mul_vecMulVec, ← dotProduct_mulVec, vecMulVec_smul]

/-- **Isometry** for a `(−2)`-vector: if `L` is symmetric and `vᵀLv = -2`, then
`s_vᵀ L s_v = L`, i.e. `reflection L v` preserves the bilinear form `L`. This is the Lean
content behind the module docstring's sympy-checked general identity
`s_vᵀ L s_v − L = (2 + vᵀLv)·L v vᵀ L`: at `vᵀLv = -2` the right-hand side's coefficient
vanishes, which is exactly what this proof verifies directly (not by invoking that
unproved general identity). -/
theorem reflection_isometry (L : Gram n) (hL : Lᵀ = L) (v : Fin n → ℤ)
    (hv : latticeNorm L v = -2) :
    (reflection L v)ᵀ * L * reflection L v = L := by
  -- the "error term" `(v vᵀ L)(v vᵀ L)` collapses to `-2 • (v vᵀ L)` using `vᵀLv = -2`.
  have key := vecMulVec_mul_self L v
  have hPP : vecMulVec v v * L * (vecMulVec v v * L) = (-2 : ℤ) • (vecMulVec v v * L) := by
    rw [← mul_assoc, key, hv, smul_mul_assoc]
  -- transpose of `reflection L v`, using symmetry of `L` (`hL`) to move `L` to the left.
  have hT : (reflection L v)ᵀ = 1 + L * vecMulVec v v := by
    unfold reflection
    rw [transpose_add, transpose_one, transpose_mul, transpose_vecMulVec, hL]
  rw [hT]
  unfold reflection
  -- expand `(1 + L v vᵀ) L (1 + v vᵀ L)` into four terms; the fourth is the error term.
  have expand : (1 + L * vecMulVec v v) * L * (1 + vecMulVec v v * L)
      = L + L * (vecMulVec v v * L) + L * (vecMulVec v v * L)
        + L * (vecMulVec v v * L * (vecMulVec v v * L)) := by
    noncomm_ring
  -- substitute the error term (`hPP`), which cancels the two middle `+L·(v vᵀ L)` terms
  -- against the `-2 •` factor, leaving exactly `L`.
  rw [expand, hPP, mul_smul_comm]
  abel

/-- **Involution** for a `(−2)`-vector: `s_v² = 1` whenever `vᵀLv = -2` — no symmetry
hypothesis on `L` is needed for this direction, only for `reflection_isometry`. This
is the other half of "reflections are order-2 lattice isometries". -/
theorem reflection_involution (L : Gram n) (v : Fin n → ℤ) (hv : latticeNorm L v = -2) :
    reflection L v * reflection L v = 1 := by
  -- same error-term collapse as in `reflection_isometry`, here needed for `s_v * s_v`.
  have key := vecMulVec_mul_self L v
  have hPP : vecMulVec v v * L * (vecMulVec v v * L) = (-2 : ℤ) • (vecMulVec v v * L) := by
    rw [← mul_assoc, key, hv, smul_mul_assoc]
  -- expand `(1 + v vᵀ L)²` and substitute the error term; the two linear terms and the
  -- `-2 •` quadratic term sum to `1`.
  show (1 + vecMulVec v v * L) * (1 + vecMulVec v v * L) = 1
  simp only [add_mul, mul_add, one_mul, mul_one, hPP]
  abel

/-- Each of the 8 standard basis vectors `eᵢ`, i.e. each simple root of `E8(−1)`
(in the Dynkin labelling of `E8.lean`), has norm `−2` — the normalization exceptional
`(−2)`-curve classes carry (module docstring). -/
theorem e8Neg_simpleRoot_norm (i : Fin 8) : latticeNorm e8Neg (Pi.single i 1) = -2 := by
  fin_cases i <;>
    simp [latticeNorm, Matrix.mulVec, dotProduct, e8Neg, cartanE8, Pi.single_apply]

/-- Each of the 8 *simple* Weyl reflections is an isometry of `E8(−1)`: an immediate
instance of `reflection_isometry` at each simple root, using `e8Neg_symm` for symmetry
and `e8Neg_simpleRoot_norm` for the `-2` norm hypothesis. This covers only the 8
generators, not the full 240-root Weyl group of `E8` (see "Mathematical content" above). -/
theorem e8Neg_weyl_isometry (i : Fin 8) :
    (reflection e8Neg (Pi.single i 1))ᵀ * e8Neg * reflection e8Neg (Pi.single i 1) = e8Neg :=
  reflection_isometry e8Neg e8Neg_symm _ (e8Neg_simpleRoot_norm i)

end DualScaleStream2.Lattice
