/-
Stream 8 · E4 — the forger's test for the symmetries of the Kummer structure.

E3 (`KummerE3.lean`) showed that the Kummer split `24 = 8 + 16` is the octad split of the extended Golay code.
E4 asks whether the symmetries of that structure pass the test the 27720 lock failed: do they act on the 24 points
as genuine elements of `M₂₄`, and do their twined genera match what K3 geometry demands?

### Sources (Tier L)
* Huybrechts (`huybrechts_K3Global.txt`), Ch. 15, Cor. 1.5, ll. 14030–14040: a symplectic automorphism `f` of
  order `n` of a complex K3 has finitely many fixed points, at least one, and `|Fix(f)| = 24 / (n ∏_{p | n} (1 + 1/p))`
  (Nikulin, Mukai). Cor. 1.8, ll. 14117–14135: `n ≤ 8`, from `dim H*(X)^f ≥ 5`. Thm. 3.1 (Mukai), ll. 14545–14556:
  a finite group acts faithfully and symplectically on some K3 iff it embeds in `M₂₃` with at least five orbits on
  the 24 points.
* Taormina–Wendland (`1107_3834.txt`), ll. 2084–2090, 2491–2507: their overarching group `(ℤ₂)⁴ ⋊ A₇` is the
  stabilizer, inside `M₂₃` (the stabilizer of one label), of an octad containing that label. It is generated by four
  involutions `ι₁ … ι₄`, which fix the octad pointwise, and by elements acting as `A₇` on the other seven octad
  points. It contains the symplectic automorphism group of every Kummer surface with induced Kähler class
  (Thm. 4.4.1).
* CDH Table 14 (via `TwinedHilbert.frameShape`): the Frame shapes of the 26 classes of `M₂₄`.
* Huybrechts ll. 14623–14633: the extended Golay code `W ⊂ 𝔽₂²⁴` (dimension 12, minimum weight 8) is unique up to
  coordinate permutation, `M₂₄ := {σ ∈ S₂₄ | σ(W) = W}`, and `M₂₄` is 5-transitive. So a permutation preserving
  `KummerE3.golay` (dimension 12, minimum weight 8 by `golay_code`) is an element of `M₂₄` in these coordinates.
  By 5-transitivity every 5-set lies in a unique octad and `M₂₄` is transitive on pairs (octad, point of it), so the
  stabilizer of our (octad, position 0) is conjugate in `M₂₄` to TW's group (TW l. 2500). Conjugate groups have the
  same class census.

### What is proved (Tier A)
* `mukai_classes`: among the 26 classes, those with a fixed point (i.e. in `M₂₃`) whose cyclic group has at least
  five orbits (number of cycles `≥ 5`) are exactly `1A, 2A, 3A, 4B, 5A, 6A, 7A, 7B, 8A`. They have order `≤ 8`.
* `nikulin_from_moonshine`: for each of these classes, the value of the twined genus at `z = 0`, `χ_g`
  (`twined_genus_z0`: `Z_g(τ, 0) = χ_g`), equals Nikulin's fixed-point number for its order:
  `χ_g · n · ∏ (p + 1) = 24 · ∏ p`. So the moonshine data (Stream 4) reproduce the geometric fixed-point table:
  8, 6, 4, 4, 2, 3, 2 for `n = 2 … 8`.
* `kummer_translations`: four explicit permutations of the 24 positions of `KummerE3.golay` preserve the Golay
  code, fix the octad pointwise, commute, are involutions, and on the 16 complement points act as translations of
  `𝔽₂⁴`. Their Frame shape is `1⁸2⁸`, class `2A`. With `nikulin_from_moonshine` this gives 8 fixed points, the
  number for a Nikulin involution, and the value Mukai's theorem requires for the half-period translations of a
  Kummer surface.
* `tw_generators`: two further Golay automorphisms that fix position 0 and the octad setwise. Together with the
  translations they generate the octad-and-point stabilizer; that the generated group has order 40320 is a
  computation (`tools/e4_octad_census.py`), not a kernel check.
* `frame_classes_up_to_pairs`: the 26 Frame shapes take 21 values; the only coincidences are the five pairs
  `7A/7B`, `14A/14B`, `15A/15B`, `21A/21B`, `23A/23B`. A Frame shape therefore fixes the class except within
  these pairs, which is exactly how far the census below can go.
* `order14_not_geometric`: a Golay automorphism fixing position 0 and the octad has Frame shape `1·2·7·14`
  (class `14A` or `14B`), hence only four orbits. By Mukai's theorem no K3 surface has it as a symplectic
  automorphism, although its twined genus is one of the 26 computed.

### Computation (not kernel-checked; `tools/e4_octad_census.py`)
The octad stabilizer has order 322560 (`2⁴:A₈`), its point stabilizer 40320 (`2⁴:A₇`). Classes in `2⁴:A₇`, by Frame
shape: `1A` 1, `2A` 435, `3A` 2240, `4B` 6300, `5A` 8064, `6A` 6720, `7A/B` 5760, `8A` 5040, `14A/B` 5760. So
`34560` of its `40320` elements are in Mukai's nine classes, and `5760` (order 14) are not.

### Reading (Tier C) and scope
The symmetries of the E3 structure pass the forger's test: every element has a Frame shape of `M₂₄`, hence a twined
genus among the 26 computed. On the geometric classes these genera give exactly Nikulin's fixed points. The group
is not the symmetry group of one K3: its order-14 elements are symmetries of the family of Kummer surfaces as a
whole (TW), not of any single surface. The Frame shape does not decide between the pairs `7A/7B` and `14A/14B`.
The symplectic group of the Kummer surface on the `τ = ω` ray (`D = 12`, E2 ∩ E3) is not determined here.
-/
import DualScaleDyons.KummerE3
import DualScaleDyons.TwistedDyons

namespace DualScaleDyons.ForgerE4

open DualScaleDyons.KummerE3 DualScaleMoonshine

/-! ### Frame-shape data: Mukai's classes and Nikulin's fixed points -/

/-- Order of a class: the lcm of its cycle lengths. -/
def classOrder (j : ℕ) : ℕ := ((frameShape.getD j []).map (·.1)).foldl Nat.lcm 1

/-- Number of cycles, i.e. of orbits of the cyclic group on the 24 points. -/
def cycles (j : ℕ) : ℕ := ((frameShape.getD j []).map (·.2)).sum

/-- Fixed points `e₁`. -/
def fixedPts (j : ℕ) : ℕ := ((frameShape.getD j []).filter (·.1 = 1)).foldl (fun a f => a + f.2) 0

/-- Mukai's criterion for a cyclic group: in `M₂₃` (a fixed point) with at least five orbits. -/
def geometric (j : ℕ) : Bool := decide (1 ≤ fixedPts j) && decide (5 ≤ cycles j)

def primesDividing (n : ℕ) : List ℕ := [2, 3, 5, 7, 11, 13, 17, 19, 23].filter (fun p => n % p = 0)

/-- **Mukai's classes.** Exactly `1A, 2A, 3A, 4B, 5A, 6A, 7A, 7B, 8A` (indices in CDH's order), all of order `≤ 8`. -/
theorem mukai_classes :
    (List.range 26).filter geometric = [0, 1, 3, 6, 8, 9, 11, 12, 13] ∧
      ((List.range 26).filter geometric).all (fun j => classOrder j ≤ 8) = true := by
  decide +kernel

/-- **Nikulin's fixed points from the moonshine data.** On Mukai's classes, `χ_g = Z_g(τ, 0)` satisfies
`χ_g · n · ∏_{p | n} (p + 1) = 24 · ∏_{p | n} p` (Huybrechts Cor. 15.1.5). -/
theorem nikulin_from_moonshine :
    ((List.range 26).filter geometric).all (fun j =>
      chiShadow.getD j 0 * (classOrder j : ℤ) * (((primesDividing (classOrder j)).map (· + 1)).prod : ℕ) =
        24 * ((primesDividing (classOrder j)).prod : ℕ)) = true ∧
      ((List.range 26).filter geometric).map (fun j => chiShadow.getD j 0) = [24, 8, 6, 4, 4, 2, 3, 3, 2] ∧
      (List.range 26).all (fun j => (zTw j 4).map LP.eval1 == [chiShadow.getD j 0, 0, 0, 0, 0]) = true :=
  ⟨by decide +kernel, by decide +kernel, twined_genus_z0⟩

/-- **What a Frame shape determines.** 21 distinct shapes; the repeated ones are exactly the five `A/B` pairs. -/
theorem frame_classes_up_to_pairs :
    frameShape.dedup.length = 21 ∧
      (List.range 26).filter (fun j => 2 ≤ (frameShape.filter (· == frameShape.getD j [])).length) =
        [11, 12, 18, 19, 20, 21, 22, 23, 24, 25] ∧
      [(11, 12), (18, 19), (20, 21), (22, 23), (24, 25)].all (fun ab =>
        frameShape.getD ab.1 [] == frameShape.getD ab.2 []) = true := by
  decide +kernel

/-! ### Explicit Golay automorphisms (permutations of the 24 positions of `KummerE3.golay`) -/

/-- Image of a bitmask under a permutation `p` (position `i ↦ p[i]`). -/
def act (p : List ℕ) (w : ℕ) : ℕ :=
  (List.range 24).foldl (fun m i => if w.testBit i then m + 2 ^ (p.getD i 0) else m) 0

def isPerm (p : List ℕ) : Bool := p.length == 24 && (List.range 24).all (· ∈ p)

/-- `p` maps the Golay basis into the code; being a permutation, it is then an automorphism of the code. -/
def preservesGolay (p : List ℕ) : Bool := golayBasis.all (fun b => act p b ∈ golay)

/-- Composition `p ∘ q`. -/
def comp2 (p q : List ℕ) : List ℕ := q.map (fun i => p.getD i 0)

def iter (p : List ℕ) : ℕ → ℕ → ℕ
  | 0, i => i
  | k + 1, i => p.getD (iter p k i) 0

/-- Length of the cycle through `i`. -/
def orbitLen (p : List ℕ) (i : ℕ) : ℕ := ((List.range 24).find? (fun k => iter p (k + 1) i = i)).getD 23 + 1

/-- Frame shape `[(k, e_k)]` of a permutation of 24 points. -/
def frameOf (p : List ℕ) : List (ℕ × ℕ) :=
  ((List.range 24).map (· + 1)).filterMap fun k =>
    let c := ((List.range 24).filter fun i => orbitLen p i = k).length / k
    if c = 0 then none else some (k, c)

/-- The octad positions `{0, 2, 5, 8, 9, 10, 11, 12}`. -/
def octadPts : List ℕ := (List.range 24).filter fun i => octad.testBit i

/-- The four half-period translations (TW's `ι₁ … ι₄`): `x ↦ x + eᵢ` on the complement, transported by `φ`. -/
def kummerTrans : List (List ℕ) :=
  [ [0, 14, 2, 17, 21, 5, 15, 16, 8, 9, 10, 11, 12, 22, 1, 6, 7, 3, 20, 23, 18, 4, 13, 19],
    [0, 22, 2, 15, 7, 5, 17, 4, 8, 9, 10, 11, 12, 14, 13, 3, 21, 6, 19, 18, 23, 16, 1, 20],
    [0, 3, 2, 1, 19, 5, 13, 18, 8, 9, 10, 11, 12, 6, 17, 22, 20, 14, 7, 4, 16, 23, 15, 21],
    [0, 20, 2, 16, 6, 5, 4, 17, 8, 9, 10, 11, 12, 19, 18, 21, 3, 7, 14, 13, 1, 15, 23, 22] ]

/-- Position ↦ point of `𝔽₂⁴` (through `φ`), and back. -/
def toF (pos : ℕ) : ℕ := phi.getD (comp.idxOf pos) 0
def ofF (x : ℕ) : ℕ := comp.getD (phi.idxOf x) 0

/-- The action of a permutation on the complement, read in `𝔽₂⁴`. -/
def onF (t : List ℕ) (x : ℕ) : ℕ := toF (t.getD (ofF x) 0)

/-- **The Kummer translations are Golay automorphisms of class `2A`**, acting on the complement as `x ↦ x + eᵢ`. -/
theorem kummer_translations :
    kummerTrans.all (fun t => isPerm t && preservesGolay t && octadPts.all (fun i => t.getD i 0 == i) &&
      comp2 t t == List.range 24 && frameOf t == [(1, 8), (2, 8)]) = true ∧
      kummerTrans.all (fun s => kummerTrans.all fun t => comp2 s t == comp2 t s) = true ∧
      frameShape.getD 1 [] = [(1, 8), (2, 8)] ∧
      kummerTrans.all (fun t => (List.range 16).all fun x => onF t x == (x ^^^ onF t 0)) = true ∧
      kummerTrans.map (fun t => onF t 0) = [1, 2, 4, 8] := by
  decide +kernel

/-- Two generators, with the translations, of the stabilizer of position 0 and of the octad. -/
def genA : List ℕ := [0, 4, 11, 22, 23, 10, 15, 17, 2, 8, 5, 9, 12, 19, 3, 7, 21, 18, 20, 6, 13, 14, 1, 16]
def genB : List ℕ := [0, 17, 8, 7, 15, 2, 6, 22, 11, 10, 12, 9, 5, 4, 19, 18, 16, 13, 23, 21, 3, 20, 14, 1]

theorem tw_generators :
    [genA, genB].all (fun g => isPerm g && preservesGolay g && act g octad == octad && g.getD 0 1 == 0 &&
      (frameShape.contains (frameOf g))) = true := by
  decide +kernel

/-- An element of order 14 in the stabilizer of position 0 and of the octad. -/
def g14 : List ℕ := [0, 21, 11, 14, 15, 9, 7, 20, 2, 12, 8, 5, 10, 22, 16, 4, 23, 13, 6, 18, 17, 3, 1, 19]

/-- **Not geometric.** `g14` is a Golay automorphism fixing position 0 and the octad; its Frame shape `1·2·7·14`
is that of `14A`/`14B`, with only four orbits, so (Mukai) it is a symplectic automorphism of no K3 surface. -/
theorem order14_not_geometric :
    (isPerm g14 && preservesGolay g14 && act g14 octad == octad && g14.getD 0 1 == 0) = true ∧
      frameOf g14 = [(1, 1), (2, 1), (7, 1), (14, 1)] ∧
      frameShape.getD 18 [] = frameOf g14 ∧ frameShape.getD 19 [] = frameOf g14 ∧
      geometric 18 = false ∧ geometric 19 = false := by
  decide +kernel

end DualScaleDyons.ForgerE4
