import Proofs.Proof01
import Proofs.Proof02
import Proofs.Proof03
import Proofs.Proof04
import Proofs.Proof05
import Proofs.Proof06
import Proofs.Proof07
import Proofs.Proof08
import Proofs.Proof09
import Proofs.Proof10
import Proofs.Proof11
import Proofs.Proof12
import Proofs.Proof13
import Proofs.Proof14
import Proofs.Proof15
import Proofs.Proof16
import Proofs.Proof17
import Proofs.Proof18
import Proofs.Proof19
import Proofs.Proof20
import Proofs.Proof21
import Proofs.Proof22
import Proofs.Proof23
import Proofs.Proof24
import Proofs.Proof25
import Proofs.Proof26
import Proofs.Proof27
import Proofs.Proof28
import Proofs.Proof29
import Proofs.Proof30
import Proofs.Proof31
import Proofs.Proof32
import Proofs.Proof33
import Proofs.Proof34
import Proofs.Proof35
import Proofs.Proof36
