import Specs.Card01
import Specs.Card02
import Specs.Card03
import Specs.Card04
import Specs.Card05
import Specs.Card06
import Specs.Card07
import Specs.Card08
import Specs.Card09
import Specs.Card10
import Specs.Card11
import Specs.Card12
import Specs.Card13
import Specs.Card14
import Specs.Card15
import Specs.Card16
import Specs.Card17
import Specs.Card18
import Specs.Card19
import Specs.Card20
import Specs.Card21
import Specs.Card22
import Specs.Card23
import Specs.Card24
import Specs.Card25
import Specs.Card26
import Specs.Card27
import Specs.Card28
import Specs.Card29
import Specs.Card30
import Specs.Card31
import Specs.Card32
import Specs.Card33
import Specs.Card34
import Specs.Card35
import Specs.Card36
