#!/usr/bin/env python3
"""
tools/book_assemble.py — assemble papers/book/book.tex from chapters.json and generate
Appendix B (index of every source-level theorem, by library and module).

  python3 tools/book_assemble.py          # writes book.tex + generated/theorem_index.tex
  cd papers/book && pdflatex book && makeindex book && pdflatex book && pdflatex book
"""
import json
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOOK = ROOT / "papers" / "book"


def tex(s: str) -> str:
    s = s.replace("\\", " ").replace("{", "(").replace("}", ")")
    for a, b in [("_", r"\_"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("$", r"\$"), ("^", r"\^{}"), ("~", r"\~{}")]:
        s = s.replace(a, b)
    return s


def theorem_index() -> int:
    db = sqlite3.connect(ROOT / ".leancache" / "declarations.db")
    rows = db.execute("select repository,module,name,docstring from declarations "
                      "where decl_type='theorem' order by repository,module,name").fetchall()
    own = ["DualScaleStream2", "StringTheoryFormalization", "DoubleFieldTheory", "DualScaleM24Formalization",
           "StringTheoryFoundation", "DualScaleValidation", "Lean5Corpus"]
    out = []
    n = 0
    for lib in own:
        lrows = [r for r in rows if r[0] == lib]
        if not lrows:
            continue
        out.append(rf"\section*{{\texttt{{{tex(lib)}}} ({len(lrows)} theorems)}}")
        out.append(r"\begin{longtable}{p{0.40\textwidth}p{0.55\textwidth}}\toprule Theorem & First line of its docstring \\ \midrule\endhead\bottomrule\endfoot")
        mod = None
        for _, m, name, doc in lrows:
            if m != mod:
                mod = m
                out.append(rf"\multicolumn{{2}}{{l}}{{\textsf{{\small {tex(m)}}}}} \\")
            d = re.sub(r"\s+", " ", re.sub(r"[#*`$]", "", (doc or ""))).strip()
            d = d.encode("ascii", "ignore").decode()[:150]
            out.append(rf"\quad\texttt{{\footnotesize {tex(name)}}} & {{\footnotesize {tex(d)}}} \\")
            n += 1
        out.append(r"\end{longtable}")
    (BOOK / "generated" / "theorem_index.tex").write_text("\n".join(out) + "\n")
    return n


def main() -> None:
    plan = json.loads((BOOK / "chapters.json").read_text())
    n = theorem_index()
    body = []
    for part in plan["parts"]:
        chs = [c for c in plan["chapters"] if c["part"] == part["id"] and (BOOK / c["file"]).exists()]
        if not chs:
            continue
        title = part["title"].replace("×", r"$\times$").replace("²", r"$^2$")
        body.append(r"\part{" + title + "}")
        body += [rf"\include{{{c['file'][:-4]}}}" for c in chs]
    book = r"""% GENERATED by tools/book_assemble.py — edit frontmatter.tex / appendices.tex / chapters, not this file.
\documentclass[11pt,twoside,openright]{book}
\input{preamble}
\begin{document}
\frontmatter
\input{frontmatter}
\tableofcontents
\mainmatter
""" + "\n".join(body) + r"""
\appendix
\input{appendices}
\backmatter
\input{bibliography}
\printindex
\end{document}
"""
    (BOOK / "book.tex").write_text(book)
    print(f"book.tex written; theorem index: {n} theorems")


if __name__ == "__main__":
    main()
