#!/usr/bin/env python3
"""
tools/e4_octad_census.py — Stream 8 E4: the group generated by the Golay automorphisms of
DualScaleDyons/ForgerE4.lean, and the M24 classes (by Frame shape) of its elements.

A computation, not a kernel check. It rebuilds the extended Golay code exactly as KummerE3.lean does
(quadratic residues mod 23, extended by parity), checks that each generator preserves it, generates
  * the octad stabilizer  <kummerTrans, octad-linear generators>          (expected 322560 = |2^4:A8|)
  * the octad-and-point stabilizer <kummerTrans, genA, genB>             (expected 40320  = |2^4:A7|)
and prints the Frame-shape census. Usage: python3 tools/e4_octad_census.py
"""
import collections

QR = sorted({(y * y) % 23 for y in range(1, 23)})


def qr_shift(k):
    s = 0
    for x in QR:
        s |= 1 << ((x + k) % 23)
    return s | ((bin(s).count("1") % 2) << 23)


BASIS = [qr_shift(k) for k in range(12)]
GOLAY = {0}
for b in BASIS:
    GOLAY |= {g ^ b for g in GOLAY}
assert len(GOLAY) == 4096
OCTAD = 7973
KUMMER_TRANS = [
    [0, 14, 2, 17, 21, 5, 15, 16, 8, 9, 10, 11, 12, 22, 1, 6, 7, 3, 20, 23, 18, 4, 13, 19],
    [0, 22, 2, 15, 7, 5, 17, 4, 8, 9, 10, 11, 12, 14, 13, 3, 21, 6, 19, 18, 23, 16, 1, 20],
    [0, 3, 2, 1, 19, 5, 13, 18, 8, 9, 10, 11, 12, 6, 17, 22, 20, 14, 7, 4, 16, 23, 15, 21],
    [0, 20, 2, 16, 6, 5, 4, 17, 8, 9, 10, 11, 12, 19, 18, 21, 3, 7, 14, 13, 1, 15, 23, 22]]
GEN_A = [0, 4, 11, 22, 23, 10, 15, 17, 2, 8, 5, 9, 12, 19, 3, 7, 21, 18, 20, 6, 13, 14, 1, 16]
GEN_B = [0, 17, 8, 7, 15, 2, 6, 22, 11, 10, 12, 9, 5, 4, 19, 18, 16, 13, 23, 21, 3, 20, 14, 1]
# a transvection and a coordinate cycle of F_2^4, completed on the octad (found by search, see ForgerE4 docs)
LIN = []
PHI = [10, 14, 5, 13, 7, 9, 11, 12, 6, 15, 3, 1, 2, 4, 8, 0]
O = [i for i in range(24) if OCTAD >> i & 1]
C = [i for i in range(24) if not OCTAD >> i & 1]
PT = {C[j]: PHI[j] for j in range(16)}
INV = {v: k for k, v in PT.items()}


def act(p, w):
    return sum(1 << p[i] for i in range(24) if w >> i & 1)


def preserves(p):
    return sorted(p) == list(range(24)) and all(act(p, b) in GOLAY for b in BASIS)


def lin_perm(cols, sigma):
    p = list(range(24))
    for c in C:
        v = PT[c]
        p[c] = INV[(cols[0] if v & 1 else 0) ^ (cols[1] if v & 2 else 0) ^ (cols[2] if v & 4 else 0)
                   ^ (cols[3] if v & 8 else 0)]
    for i, o in enumerate(O):
        p[o] = O[sigma[i]]
    return p


LIN = [lin_perm([1, 2, 4, 9], (6, 7, 5, 4, 3, 2, 0, 1)), lin_perm([2, 4, 8, 1], (7, 1, 3, 2, 4, 0, 5, 6))]


def closure(gens):
    idt = tuple(range(24))
    seen, frontier = {idt}, [idt]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = tuple(g[x[i]] for i in range(24))
                if y not in seen:
                    seen.add(y)
                    nxt.append(y)
        frontier = nxt
    return seen


def frame(p):
    vis, c = [False] * 24, collections.Counter()
    for i in range(24):
        if not vis[i]:
            n, j = 0, i
            while not vis[j]:
                vis[j], j, n = True, p[j], n + 1
            c[n] += 1
    return tuple(sorted(c.items()))


NAMES = {((1, 24),): "1A", ((1, 8), (2, 8)): "2A", ((2, 12),): "2B", ((1, 6), (3, 6)): "3A", ((3, 8),): "3B",
         ((2, 4), (4, 4)): "4A", ((1, 4), (2, 2), (4, 4)): "4B", ((4, 6),): "4C", ((1, 4), (5, 4)): "5A",
         ((1, 2), (2, 2), (3, 2), (6, 2)): "6A", ((6, 4),): "6B", ((1, 3), (7, 3)): "7A/B",
         ((1, 2), (2, 1), (4, 1), (8, 2)): "8A", ((2, 2), (10, 2)): "10A", ((1, 2), (11, 2)): "11A",
         ((2, 1), (4, 1), (6, 1), (12, 1)): "12A", ((12, 2),): "12B", ((1, 1), (2, 1), (7, 1), (14, 1)): "14A/B",
         ((1, 1), (3, 1), (5, 1), (15, 1)): "15A/B", ((3, 1), (21, 1)): "21A/B", ((1, 1), (23, 1)): "23A/B"}

if __name__ == "__main__":
    gens = KUMMER_TRANS + [GEN_A, GEN_B] + LIN
    assert all(preserves(g) for g in gens), "a generator does not preserve the Golay code"
    for name, gs in (("octad stabilizer 2^4:A8", KUMMER_TRANS + LIN), ("point stabilizer 2^4:A7", KUMMER_TRANS + [GEN_A, GEN_B])):
        grp = closure(gs)
        assert all(act(p, OCTAD) == OCTAD for p in grp)
        cen = collections.Counter(NAMES[frame(p)] for p in grp)
        print(f"{name}: order {len(grp)}")
        print("  " + ", ".join(f"{k} {v}" for k, v in sorted(cen.items(), key=lambda kv: (int(''.join(filter(str.isdigit, kv[0]))), kv[0]))))
