#!/usr/bin/env python3
"""
tools/insert_paper_figures.py — place the computed figures of tools/book_figures.py into the papers.

Idempotent: each inserted block is fenced by `% [fig:<name>]` markers and is replaced, not duplicated, on
re-run. Captions come from papers/book/generated/figures/figures.json (the single source of truth);
Markdown code spans become \\texttt.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUB = ROOT / "papers" / "publication"
FIGS = {f["name"]: f for f in json.loads((ROOT / "papers/book/generated/figures/figures.json").read_text())}

# paper file prefix -> [(figure name, regex of the line AFTER which the figure goes)]
PLACEMENT = {
    "paper1_": [("circle_spectrum", r"\\section\{Generalized Geometry and Double Field Theory\}"),
                ("dual_scale_bound", r"\\section\{Physical Discussion\}")],
    "paper2_": [("moonshine_coefficients", r"\\section\{BPS Multiplicity Rigidity")],
    "paper7_": [("k3_hodge_diamond", r"\\section\{Compactification on"),
                ("dual_scale_bound", r"\\section\{The Effective Dual Scale"),
                ("moonshine_coefficients", r"\\section\{Mathieu \\texorpdfstring"),
                ("circle_spectrum", r"\\subsection\{The T-duality group"),
                ("generalized_metric_odd", r"\\subsection\{Double Field Theory over"),
                ("atlas_dependency_graph", r"\\subsection\{How Stream 2 was produced")],
    "paper8_": [("e8_k3_gram", r"\\subsection\{Signature bookkeeping"),
                ("circle_spectrum", r"\\subsection\{Factorized dualities and spectrum equivalence\}"),
                ("narain_lattice_circle", r"\\subsection\{Factorized dualities and spectrum equivalence\}"),
                ("modular_fundamental_domain", r"\\subsection\{\$SL\(2,\\mathbb\{Z\}\)\\times"),
                ("generalized_metric_odd", r"\\subsection\{\$B\$-field shifts\}"),
                ("dual_scale_bound", r"\\section\{The dual-scale trace bound\}"),
                ("tadpole_budget", r"\\section\{Flux and tadpole cancellation"),
                ("moonshine_coefficients", r"\\section\{Mathieu moonshine arithmetic\}"),
                ("atlas_dependency_graph", r"\\subsection\{Measured results\}")],
}


UNICODE = {"α′": r"$\alpha'$", "α": r"$\alpha$", "′": "'", "–": "--", "—": "---", "≥": r"$\ge$", "≤": r"$\le$",
           "²": r"$^2$", "→": r"$\to$", "↦": r"$\mapsto$", "−": "-", "Σ": r"$\Sigma$", "χ": r"$\chi$",
           "∈": r"$\in$", "η": r"$\eta$", "ᵀ": r"$^{\mathsf T}$", "±": r"$\pm$", "§": r"\S{}", "₂": r"$_2$"}


def caption_tex(s: str) -> str:
    parts = s.split("`")  # even indices: prose, odd indices: code spans

    def prose(p: str) -> str:  # escape only outside $...$ so math subscripts survive
        segs = p.split("$")
        return "$".join(x if j % 2 else x.replace("_", r"\_").replace("#", r"\#") for j, x in enumerate(segs))
    s = "".join(r"\texttt{" + p.replace("_", r"\_") + "}" if i % 2 else prose(p) for i, p in enumerate(parts))
    for k in sorted(UNICODE, key=len, reverse=True):
        s = s.replace(k, UNICODE[k])
    bad = sorted({c for c in s if ord(c) > 127})
    if bad:
        raise SystemExit(f"unmapped unicode in caption: {bad}")
    return s


def block(name: str) -> str:
    f = FIGS[name]
    return (f"% [fig:{name}] generated by tools/insert_paper_figures.py from tools/book_figures.py\n"
            "\\begin{figure}[tbp]\n\\centering\n"
            f"\\includegraphics[width=\\linewidth]{{{name}.pdf}}\n"
            f"\\caption{{{caption_tex(f['caption'])} \\emph{{Computed figure; data: {caption_tex(f['source'])}.}}}}\n"
            f"\\label{{fig:{name}}}\n\\end{{figure}}\n% [/fig:{name}]\n")


def main() -> None:
    for prefix, items in PLACEMENT.items():
        path = next(PUB.glob(prefix + "*.tex"))
        t = path.read_text()
        t = re.sub(r"% \[fig:[^\]]*\].*?% \[/fig:[^\]]*\]\n", "", t, flags=re.S)
        if "\\usepackage{graphicx}" not in t:
            t = t.replace("\\begin{document}", "\\usepackage{graphicx}\n\\begin{document}", 1)
        if "\\graphicspath" not in t:
            t = t.replace("\\begin{document}", "\\graphicspath{{../book/generated/figures/}}\n\\begin{document}", 1)
        for name, anchor in reversed(items):
            m = re.search(anchor + r"[^\n]*\n", t)
            if not m:
                raise SystemExit(f"{path.name}: anchor not found: {anchor}")
            t = t[:m.end()] + block(name) + t[m.end():]
        path.write_text(t)
        print(f"{path.name}: {len(items)} figures")


if __name__ == "__main__":
    main()
