#!/usr/bin/env python3
"""
tools/theorem_atlas.py — RAG + graph "atlas" of the project's theorems, for the master book.

Inputs
  .leancache/depgraph.jsonl   kernel-level dependencies (tools/lean_depgraph.lean)
  .leancache/declarations.db  signatures + docstrings (tools/index_declarations.py)

Outputs (papers/book/generated/)
  lean_catalogue.md     per-module list of declarations with statement + docstring head (RAG context)
  atlas.md              human-readable findings: hubs, bridges, similar pairs, shared foundations
  atlas_data.json       the same, machine-readable
  atlas_tables.tex      longtable fragments \\input by the Atlas chapter
  module_graph.dot      module-level dependency graph (rendered to PDF if `dot` is available)

Two independent notions of "related theorems" are reported, and kept separate on purpose:
  * INTERSECTION (graph): two theorems share kernel-level dependencies. Jaccard index of the
    sets of constants their statements and proofs use, weighted by inverse document frequency so
    that sharing `Eq` counts for nothing and sharing `Matrix.fromBlocks_multiply` counts for a lot.
  * SIMILARITY (text/RAG): TF-IDF cosine similarity between statements + docstrings.
A pair that scores high on similarity but zero on intersection is a candidate for unification:
the same mathematics formalized twice without one proof using the other.
"""

import collections
import json
import math
import re
import shutil
import sqlite3
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "papers" / "book" / "generated"
LIBS = ["DualScaleStream2", "StringTheoryFormalization", "DoubleFieldTheory",
        "DualScaleM24Formalization", "StringTheoryFoundation", "DualScaleValidation", "Lean5Corpus"]
AUTO = re.compile(r"\.(noConfusion|noConfusionType|rec|recOn|casesOn|below|brecOn|binductionOn|ibelow|"
                  r"sizeOf_spec|injEq|inj|ctorIdx|match_\d+|proof_\d+|eq_\d+|_sizeOf_\d+|_unsafe_rec|"
                  r"mk|ext|ext_iff|toCtorIdx|ofNat|_sunfold|_unary|_mutual|eq_def|eq_unfold)($|\.)|^inst|\.inst|_aux|\._")


def lib_of(module: str) -> str:
    return module.split(".")[0]


def tex(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}").replace("_", r"\_").replace("&", r"\&")
             .replace("%", r"\%").replace("#", r"\#").replace("^", r"\^{}").replace("{", "{").replace("}", "}"))


def short(name: str) -> str:
    return name.split(".")[-1]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    decls = {}
    for line in (ROOT / ".leancache" / "depgraph.jsonl").read_text().splitlines():
        if not line.startswith("{"):
            continue
        d = json.loads(line)
        if AUTO.search(d["name"]):
            continue
        decls[d["name"]] = d
    own = set(decls)
    kernel_theorems = {n for n, d in decls.items() if d["kind"] == "theorem"}

    # ---- text side (RAG): signatures + docstrings from the SQLite index -------------------
    db = sqlite3.connect(ROOT / ".leancache" / "declarations.db")
    text = {}
    for name, module, sig, doc in db.execute(
            "select name,module,signature,docstring from declarations"):
        text[(module, name)] = ((sig or "").strip(), (doc or "").strip())

    # Only theorems written in the source count (structure-field projections and other
    # auto-generated theorems are kernel theorems too, but nobody stated them).
    src_theorems = {(m, n) for n, m, k in db.execute("select name,module,decl_type from declarations") if k == "theorem"}
    theorems = {n for n in kernel_theorems if (decls[n]["module"], short(n)) in src_theorems}

    def text_of(full: str):
        d = decls[full]
        return text.get((d["module"], short(full)), ("", ""))

    # ---- lean_catalogue.md ----------------------------------------------------------------
    by_mod = collections.defaultdict(list)
    for n, d in decls.items():
        by_mod[d["module"]].append(n)
    cat = ["# Lean catalogue (generated by tools/theorem_atlas.py — do not edit)\n",
           "Every declaration below exists in the compiled environment. `T` = theorem, `D` = definition,",
           "`S` = structure/inductive. Statements are from the source index; read the `.lean` file",
           "before quoting a statement in the book.\n"]
    for lib in LIBS:
        cat.append(f"\n## {lib}\n")
        for mod in sorted(m for m in by_mod if lib_of(m) == lib):
            cat.append(f"\n### {mod}  (`{mod.replace('.', '/')}.lean`)\n")
            for n in sorted(by_mod[mod]):
                k = {"theorem": "T", "def": "D", "inductive": "S"}.get(decls[n]["kind"], "?")
                sig, doc = text_of(n)
                head = re.sub(r"\s+", " ", doc)[:160]
                flat = re.sub(r"\s+", " ", sig)[:260]
                cat.append(f"- `{k}` **{n}** — `{flat}`" + (f" — {head}" if head else ""))
    (OUT / "lean_catalogue.md").write_text("\n".join(cat) + "\n")

    # ---- graph side -----------------------------------------------------------------------
    deps = {n: set(d["type"]) | set(d["value"]) for n, d in decls.items()}
    df = collections.Counter(c for n in theorems for c in deps[n])
    N = max(1, len(theorems))
    idf = {c: math.log(N / df[c]) for c in df}

    def wjacc(a: str, b: str) -> float:
        A, B = deps[a], deps[b]
        inter = sum(idf.get(c, 0) for c in A & B)
        union = sum(idf.get(c, 0) for c in A | B)
        return inter / union if union else 0.0

    # in-project hubs: own definitions/theorems used by the most own theorems
    used_by = collections.defaultdict(set)
    for n in theorems:
        for c in deps[n] & own:
            if c != n:
                used_by[c].add(n)
    hubs = sorted(used_by.items(), key=lambda kv: -len(kv[1]))[:40]

    # shared Mathlib foundations: external lemmas (theorems' proof deps) used across >=2 libraries
    ext_use = collections.defaultdict(set)
    for n in theorems:
        for c in decls[n].get("lemmas", []):
            ext_use[c].add(n)
    skip = re.compile(r"^(Eq|HEq|And|Or|Iff|Not|True|False|Nat|Int|Real|Exists|id|of_eq_true|congr|congrArg|"
                      r"eq_self|Bool|Decidable|instOfNat|OfNat|HAdd|HMul|HSub|HPow|Fin|letFun|absurd|rfl|trivial|"
                      r"propext|funext|Eq\.|And\.|Or\.|Iff\.|Nat\.|Int\.|Bool\.|Decidable\.|inst|Std\.|Lean\.|"
                      r"mul_|add_|sub_|neg_|one_|zero_|eq_|ne_|le_|lt_|of_|not_|ite|dite|Function\.|forall|implies)")
    shared = []
    for c, users in ext_use.items():
        libs = {lib_of(decls[u]["module"]) for u in users}
        if len(users) >= 3 and "." in c and not re.search(r"^(Mathlib\.Tactic|Mathlib\.Meta|of_eq_true|eq_self|congr|congrArg|Eq\.|id|rfl|trivial|propext|funext|eq_true|eq_false|of_decide|Nat\.|Int\.|Bool\.|Decidable\.|implies_true|and_self|and_true|true_and|iff_self|ne_eq|not_false|instDecidable|Fin\.|ite_|dite_|forall_|imp_self|not_true|Bool|Std\.|Lean\.|List\.|Array\.)", c):
            shared.append((c, len(users), sorted(libs), sorted(users)))
    shared.sort(key=lambda x: -x[1])
    shared = shared[:60]

    # cross-library bridges: a theorem in lib A whose statement/proof mentions a constant of lib B
    bridges = []
    for n in theorems:
        la = lib_of(decls[n]["module"])
        for c in deps[n] & own:
            lb = lib_of(decls[c]["module"])
            if lb != la:
                bridges.append((n, c, la, lb))

    # ---- similarity (TF-IDF cosine over statement + docstring + name tokens) ---------------
    tok = re.compile(r"[A-Za-z][A-Za-z0-9']{2,}|[∑∏√≤≥≠⁻ᵀ⬝∀∃]")
    docs = {}
    for n in theorems:
        sig, doc = text_of(n)
        name_toks = re.sub(r"[_.]", " ", short(n))
        docs[n] = collections.Counter(t.lower() for t in tok.findall(f"{name_toks} {name_toks} {sig} {doc[:400]}"))
    tdf = collections.Counter(t for d in docs.values() for t in d)
    vec = {}
    for n, c in docs.items():
        v = {t: (1 + math.log(f)) * math.log(N / tdf[t]) for t, f in c.items() if tdf[t] < 0.5 * N}
        norm = math.sqrt(sum(x * x for x in v.values())) or 1.0
        vec[n] = {t: x / norm for t, x in v.items()}

    def cos(a: str, b: str) -> float:
        A, B = vec[a], vec[b]
        if len(A) > len(B):
            A, B = B, A
        return sum(x * B.get(t, 0.0) for t, x in A.items())

    tl = sorted(theorems)
    sim_pairs, inter_pairs = [], []
    for i, a in enumerate(tl):
        for b in tl[i + 1:]:
            cross = lib_of(decls[a]["module"]) != lib_of(decls[b]["module"])
            s = cos(a, b)
            j = wjacc(a, b)
            if cross and s >= 0.30:
                sim_pairs.append((s, j, a, b))
            if decls[a]["module"] != decls[b]["module"] and j >= 0.35:
                inter_pairs.append((j, s, a, b))
    sim_pairs.sort(reverse=True)
    inter_pairs.sort(reverse=True)
    unify = [p for p in sim_pairs if p[1] < 0.05][:40]   # similar text, disjoint proofs
    sim_pairs, inter_pairs = sim_pairs[:60], inter_pairs[:60]

    # ---- module graph ---------------------------------------------------------------------
    medges = collections.Counter()
    for n, d in decls.items():
        for c in deps[n] & own:
            m2 = decls[c]["module"]
            if m2 != d["module"]:
                medges[(d["module"], m2)] += 1
    dot = ["digraph modules { rankdir=LR; node [shape=box,fontsize=9,fontname=Helvetica]; edge [color=gray40];"]
    colors = dict(zip(LIBS, ["lightblue", "khaki1", "lightpink", "palegreen", "lavender", "lightsalmon", "gray90"]))
    mods = sorted({m for e in medges for m in e})
    for m in mods:
        dot.append(f'  "{m}" [label="{m.split(".", 1)[-1]}",style=filled,fillcolor={colors.get(lib_of(m), "white")}];')
    for (a, b), w in medges.items():
        dot.append(f'  "{a}" -> "{b}" [penwidth={min(3.0, 0.5 + w / 6):.1f}];')
    dot.append("}")
    (OUT / "module_graph.dot").write_text("\n".join(dot) + "\n")
    if shutil.which("dot"):
        subprocess.run(["dot", "-Tpdf", str(OUT / "module_graph.dot"), "-o", str(OUT / "module_graph.pdf")], check=False)

    # ---- outputs --------------------------------------------------------------------------
    stats = {
        "declarations": len(decls), "theorems": len(theorems),
        "per_library": {lib: sum(1 for n in theorems if lib_of(decls[n]["module"]) == lib) for lib in LIBS},
        "module_edges": len(medges), "cross_library_bridges": len(bridges),
    }
    data = {
        "stats": stats,
        "hubs": [{"name": c, "kind": decls[c]["kind"], "used_by": len(u), "examples": sorted(u)[:6]} for c, u in hubs],
        "shared_foundations": [{"lemma": c, "uses": k, "libraries": libs, "examples": us[:5]} for c, k, libs, us in shared],
        "bridges": [{"theorem": n, "uses": c, "from": la, "to": lb} for n, c, la, lb in sorted(bridges)],
        "similar_cross_library": [{"cosine": round(s, 3), "dep_jaccard": round(j, 3), "a": a, "b": b} for s, j, a, b in sim_pairs],
        "intersecting": [{"dep_jaccard": round(j, 3), "cosine": round(s, 3), "a": a, "b": b} for j, s, a, b in inter_pairs],
        "unification_candidates": [{"cosine": round(s, 3), "dep_jaccard": round(j, 3), "a": a, "b": b} for s, j, a, b in unify],
    }
    (OUT / "atlas_data.json").write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n")

    md = [f"# Theorem atlas (generated)\n\n{json.dumps(stats)}\n", "## Hubs (own declarations used by most theorems)"]
    md += [f"- {h['name']} ({h['kind']}): used by {h['used_by']} theorems, e.g. {', '.join(map(short, h['examples'][:4]))}" for h in data["hubs"]]
    md += ["\n## Cross-library bridges (theorem → declaration of another library)"]
    md += [f"- {b['theorem']} → {b['uses']}" for b in data["bridges"]]
    md += ["\n## Shared external (Mathlib/core) foundations used by ≥3 theorems"]
    md += [f"- {s['lemma']}: {s['uses']} theorems in {', '.join(s['libraries'])}; e.g. {', '.join(map(short, s['examples'][:4]))}" for s in data["shared_foundations"]]
    md += ["\n## Most similar statements across libraries (TF-IDF cosine; dep-Jaccard in brackets)"]
    md += [f"- {p['cosine']} [{p['dep_jaccard']}] {p['a']}  ~  {p['b']}" for p in data["similar_cross_library"]]
    md += ["\n## Strongest dependency intersections between modules (weighted Jaccard; cosine in brackets)"]
    md += [f"- {p['dep_jaccard']} [{p['cosine']}] {p['a']}  ∩  {p['b']}" for p in data["intersecting"]]
    md += ["\n## Unification candidates: similar statements, essentially disjoint proofs"]
    md += [f"- {p['cosine']} [{p['dep_jaccard']}] {p['a']}  ~  {p['b']}" for p in data["unification_candidates"]]
    (OUT / "atlas.md").write_text("\n".join(md) + "\n")

    def table(caption, label, header, rows, spec):
        out = [rf"\begin{{longtable}}{{{spec}}}", rf"\caption{{{caption}}}\label{{{label}}}\\", r"\toprule",
               " & ".join(header) + r" \\ \midrule \endfirsthead", r"\toprule",
               " & ".join(header) + r" \\ \midrule \endhead", r"\bottomrule \endfoot"]
        out += [" & ".join(r) + r" \\" for r in rows]
        out.append(r"\end{longtable}")
        return "\n".join(out)

    def nm(full):
        return r"\texttt{\small " + tex(short(full)) + "}"

    def lb(full):
        return r"{\scriptsize " + tex(decls[full]["module"].split(".", 1)[-1] if full in decls else full) + "}"

    parts = [
        table("Hub declarations: the project's own definitions and lemmas on which the most theorems depend (kernel-level dependencies).",
              "tab:atlas-hubs", ["Declaration", "Module", "Kind", "Used by"],
              [[nm(h["name"]), lb(h["name"]), h["kind"], str(h["used_by"])] for h in data["hubs"][:30]],
              r"p{0.34\textwidth}p{0.34\textwidth}lr"),
        table("Cross-library bridges: theorems whose statement or proof uses a declaration of a different library.",
              "tab:atlas-bridges", ["Theorem", "in", "uses", "of"],
              [[nm(b["theorem"]), lb(b["theorem"]), nm(b["uses"]), lb(b["uses"])] for b in data["bridges"][:40]],
              r"p{0.26\textwidth}p{0.22\textwidth}p{0.22\textwidth}p{0.22\textwidth}"),
        table("Shared external foundations: Mathlib and core lemmas on which several of the project's theorems rest.",
              "tab:atlas-shared", ["Lemma", "Theorems", "Examples"],
              [[r"\texttt{\scriptsize " + tex(s["lemma"]) + "}", str(s["uses"]),
                ", ".join(nm(e) for e in s["examples"][:3])] for s in data["shared_foundations"][:35]],
              r"p{0.42\textwidth}rp{0.44\textwidth}"),
        table("Most similar theorem statements across libraries (TF--IDF cosine similarity), with the weighted Jaccard index of their kernel dependencies.",
              "tab:atlas-similar", ["cos", "dep", "Theorem A", "Theorem B"],
              [[f"{p['cosine']:.2f}", f"{p['dep_jaccard']:.2f}", nm(p["a"]) + r"\newline " + lb(p["a"]),
                nm(p["b"]) + r"\newline " + lb(p["b"])] for p in data["similar_cross_library"][:35]],
              r"rrp{0.40\textwidth}p{0.40\textwidth}"),
        table("Strongest dependency intersections between theorems of different modules.",
              "tab:atlas-intersect", ["dep", "cos", "Theorem A", "Theorem B"],
              [[f"{p['dep_jaccard']:.2f}", f"{p['cosine']:.2f}", nm(p["a"]) + r"\newline " + lb(p["a"]),
                nm(p["b"]) + r"\newline " + lb(p["b"])] for p in data["intersecting"][:35]],
              r"rrp{0.40\textwidth}p{0.40\textwidth}"),
    ]
    (OUT / "atlas_tables.tex").write_text("\n\n".join(parts) + "\n")
    print(json.dumps(stats, indent=1))
    print("bridges:", len(bridges), "| similar pairs:", len(sim_pairs), "| intersecting:", len(inter_pairs),
          "| unification candidates:", len(unify))


if __name__ == "__main__":
    main()
